\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{vzmsthesis}[2020/01/20 Voronezh Winter Mathematical School]

\LoadClass[a5paper,12pt,openbib]{report}


% First of all, we deal with encodings and basic fonts

\RequirePackage[utf8]{inputenc}
\RequirePackage[T2A,T1]{fontenc}
\RequirePackage[english,russian]{babel}


% Graphics and related tricks

\RequirePackage{graphics}
\RequirePackage[dvips]{graphicx}
\RequirePackage{wrapfig}
